services:
  db:
    image: postgres:15
    container_name: broketopia_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5433:5432"  # host:container

  backend:
    build:
      context: ./backend/Finance.Api
    container_name: broketopia_backend
    depends_on:
      - db
    env_file:
      - backend/Finance.Api/app.env
    environment:
      - ConnectionStrings__DefaultConnection=${DEFAULT_CONNECTION}
    ports:
      - "5000:80"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80/api/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/broketopia-ui
    container_name: broketopia_frontend
    ports:
      - "4200:80"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped


volumes:
  postgres_data:
