name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push backend
        run: |
          docker build -t youruser/finance-backend:latest ./backend/Finance.Api
          docker push youruser/finance-backend:latest

      - name: Build and push frontend
        run: |
          docker build -t youruser/finance-frontend:latest ./frontend/broketopia-ui
          docker push youruser/finance-frontend:latest

      - name: Deploy on VM
        run: |
          cd ~/Broketopia
          git pull
          docker-compose pull
          docker-compose down
          docker-compose up -d --build
